# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-28 09:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='Sensor_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 3, 28, 9, 23, 1, 329162, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
