# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-28 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_sensor_sensor_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='Sensor_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
