# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-29 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20170328_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensorgroup2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sensorgroup2_whose', models.CharField(default=None, max_length=200)),
                ('Sensorgroup2_name', models.CharField(default=None, max_length=200)),
                ('Sensorgroup2_value', models.CharField(default=None, max_length=200)),
                ('Sensorgroup2_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
