# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-29 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_sensorgroup2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorgroup2',
            name='Sensorgroup2_whose',
        ),
        migrations.AddField(
            model_name='sensorgroup2',
            name='Sensorgroup2_group',
            field=models.CharField(default='group_two', max_length=200),
        ),
    ]
